ThuVien/Areas/Admin/Controllers/NhanVienController.cs
using Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.EF;
using ThuVien.Common;

namespace ThuVien.Areas.Admin.Controllers
{
    public class NhanVienController : BaseController
    {
        // GET: Admin/NhanVien
        public ActionResult Index(string TimKiem, int Trang = 1, int KTTrang = 10)
        {
            var dao = new NhanVienDAO();
            var DSNhanVien = dao.LayDSTheoTrang(TimKiem, Trang, KTTrang);
            ViewBag.TimKiem = TimKiem;
            return View(DSNhanVien);
        }

        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemMoi(NhanVien nhanvien)
        {
            if (ModelState.IsValid)
            {
                var dao = new NhanVienDAO();

                var KetQua = dao.ThemMoi(nhanvien);

                if(KetQua > 0)
                {
                    DatThongBao("Thêm mới nhân viên thành công!", LoaiThongBao.ThanhCong);
                    return RedirectToAction("Index");
                }
                else
                {
                    DatThongBao("Thêm mới nhân viên không thành công!", LoaiThongBao.Loi);
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult CapNhat(string id)
        {
            var dao = new NhanVienDAO();
            var ThongTinNhanVien = dao.TimTheoMaNV(id);

            if (ThongTinNhanVien != null)
            {
                return View(ThongTinNhanVien);
            }
            return Redirect("/404");
        }

        [HttpPost]
        public ActionResult CapNhat(NhanVien nhanvien)
        {
            if (ModelState.IsValid)
            {
                var dao = new NhanVienDAO();

                var KetQua = dao.CapNhat(nhanvien);
                if(KetQua > 0)
                {
                    DatThongBao("Cập nhật thông tin nhân viên thành công!", LoaiThongBao.ThanhCong);
                    return RedirectToAction("Index");
                }
                else
                {
                    DatThongBao("Cập nhật thông tin nhân viên không thành công!", LoaiThongBao.Loi);
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Xoa(string id)
        {
            var dao = new NhanVienDAO();
            var NhanVien = dao.TimTheoMaNV(id);

            if(NhanVien != null)
            {
                var KetQua = dao.Xoa(id);
                if(KetQua > 0)
                {
                    DatThongBao("Xóa nhân viên thành công!", LoaiThongBao.ThanhCong);
                }
                else
                {
                    DatThongBao("Xóa nhân viên không thành công!", LoaiThongBao.Loi);
                }
                return RedirectToAction("Index");
            }
            return Redirect("/404");
        }
    }
}

ThuVien/Areas/Admin/Views/NhanVien/CapNhat.cshtml
@model Models.EF.NhanVien

@{
    ViewBag.Title = "Cập Nhật Thông Tin Nhân Viên";
    Layout = "/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Header{
    Nhân Viên
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Cập Nhật</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("CapNhat", "NhanVien", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label>Mã nhân viên</label>
                        @Html.TextBoxFor(model => model.MaNV, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.MaNV)
                    </div>
                    <div class="col">
                        <label>Họ tên</label>
                        @Html.TextBoxFor(model => model.HoTen, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.HoTen)
                    </div>
                    <div class="col">
                        <label>Chức vụ</label>
                        @Html.TextBoxFor(model => model.ChucVu, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.ChucVu)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label>Giới tính</label>
                        @Html.DropDownListFor(model => model.GioiTinh, new SelectList(new[] { "Nam", "Nữ" }), new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.GioiTinh)
                    </div>
                    <div class="col">
                        <label>Ngày sinh</label>
                        @Html.TextBoxFor(model => model.NgaySinh, "{0:yyyy-MM-dd}", new { @class = "form-control", @required = "required", @type = "date" })
                        @Html.ValidationMessageFor(model => model.NgaySinh)
                    </div>
                    <div class="col">
                        <label>Số điện thoại</label>
                        @Html.TextBoxFor(model => model.SDT, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.SDT)
                    </div>
                    <div class="col">
                        <label>Email</label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>Địa chỉ</label>
                @Html.TextBoxFor(model => model.DiaChi, new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.DiaChi)
            </div>
            <div class="form-group">
                <center>
                    <input type="submit" value="Hoàn thành" class="btn btn-primary" />
                </center>
            </div>
        }
    </div>
</div>

ThuVien/Areas/Admin/Views/NhanVien/Index.cshtml
@model PagedList.IPagedList<Models.EF.NhanVien>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Nhân Viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Header{
    Nhân Viên
}
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <span class="m-0 font-weight-bold text-primary">
            Danh sách
            <span style="float: right">

                <a href="/Admin/NhanVien/ThemMoi" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Thêm mới</span>
                </a>

            </span>
        </span>

    </div>
    <div class="card-body">
        <div class="table-responsive">

            @using (Html.BeginForm("Index", "NhanVien", FormMethod.Get))
            {
                <div style="padding: 3px; margin-bottom: 20px; width: 24.5rem">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Từ khóa" name="TimKiem" value="@ViewBag.TimKiem">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </div>
            }
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>MaNV</th>
                        <th>Họ tên</th>
                        <th>Giới tính</th>
                        <th>Số điện thoại</th>
                        <th>Email</th>
                        <th>Chức vụ</th>
                        <th style="text-align: center">Công cụ</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.MaNV</td>
                        <td>@item.HoTen</td>
                        <td>@item.GioiTinh</td>
                        <td>@item.SDT</td>
                        <td>@item.Email</td>
                        <td>@item.ChucVu</td>
                        <td align="center">
                            <a href="/Admin/NhanVien/CapNhat/@item.MaNV" class="btn btn-primary btn-circle btn-sm" title="Sửa">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="/Admin/NhanVien/Xoa/@item.MaNV" class="btn btn-danger btn-circle btn-sm" title="Xóa" data-toggle="modal" data-target="#XoaNhanVien-@item.MaNV">
                                <i class="fas fa-trash"></i>
                            </a>

                            <div class="modal fade" id="XoaNhanVien-@item.MaNV" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Xóa Nhân Viên</h5>
                                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">Xóa nhân viên này khỏi CSDL?</div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                                            <a class="btn btn-primary" href="/Admin/NhanVien/Xoa/@item.MaNV">Xóa</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    }

                </tbody>
            </table>
            @Html.PagedListPager(Model, Trang => Url.Action("Index", new { Trang, TimKiem = @ViewBag.TimKiem }))
        </div>
    </div>
</div>

ThuVien/Areas/Admin/Views/NhanVien/ThemMoi.cshtml
@model Models.EF.NhanVien

@{
    ViewBag.Title = "Thêm Mới Nhân Viên";
    Layout = "/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Header{
    Nhân Viên
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm Mới</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("ThemMoi", "NhanVien", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label>Mã nhân viên</label>
                        @Html.TextBoxFor(model => model.MaNV, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.MaNV)
                    </div>
                    <div class="col">
                        <label>Họ tên</label>
                        @Html.TextBoxFor(model => model.HoTen, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.HoTen)
                    </div>
                   <div class="col">
                        <label>Chức vụ</label>
                        @Html.TextBoxFor(model => model.ChucVu, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.ChucVu)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label>Giới tính</label>
                        @Html.DropDownListFor(model => model.GioiTinh, new SelectList(new[] { "Nam", "Nữ" }), new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.GioiTinh)
                    </div>
                    <div class="col">
                        <label>Ngày sinh</label>
                        @Html.TextBoxFor(model => model.NgaySinh, "{0:yyyy-MM-dd}", new { @class = "form-control", @required = "required", @type = "date" })
                        @Html.ValidationMessageFor(model => model.NgaySinh)
                    </div>
                    <div class="col">
                        <label>Số điện thoại</label>
                        @Html.TextBoxFor(model => model.SDT, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.SDT)
                    </div>
                    <div class="col">
                        <label>Email</label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>Địa chỉ</label>
                @Html.TextBoxFor(model => model.DiaChi, new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.DiaChi)
            </div>
            <div class="form-group">
                <center>
                    <input type="submit" value="Hoàn thành" class="btn btn-primary" />
                </center>
            </div>
        }
    </div>
</div>