ThuVien/Areas/Admin/Controllers/NguoiDungController.cs
using Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.EF;
using ThuVien.Common;

namespace ThuVien.Areas.Admin.Controllers
{
    public class NguoiDungController : BaseController
    {
        // GET: Admin/SinhVien
        public ActionResult Index(string TimKiem, int Trang = 1, int KTTrang = 10)
        {
            var dao = new NguoiDungDAO();
            var DSNguoiDung = dao.LayDSTheoTrang(TimKiem, Trang, KTTrang);
            ViewBag.TimKiem = TimKiem;
            return View(DSNguoiDung);
        }

        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemMoi(NguoiDung nguoidung)
        {
            if (ModelState.IsValid)
            {
                var dao = new NguoiDungDAO();

                if (nguoidung.MatKhau == null)
                {
                    nguoidung.MatKhau = Encryptor.MD5Hash(nguoidung.TaiKhoan);
                }
                else nguoidung.MatKhau = Encryptor.MD5Hash(nguoidung.MatKhau);

                var KetQua = dao.ThemMoi(nguoidung);

                if(KetQua > 0)
                {
                    DatThongBao("Thêm mới người dùng thành công!", LoaiThongBao.ThanhCong);
                    return RedirectToAction("Index");
                }
                else
                {
                    DatThongBao("Thêm mới người dùng không thành công!", LoaiThongBao.Loi);
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult CapNhat(string id)
        {
            var dao = new NguoiDungDAO();
            var ThongTinNguoiDung = dao.TimTheoTenTK(id);

            if (ThongTinNguoiDung != null)
            {
                ThongTinNguoiDung.MatKhau = null;
                return View(ThongTinNguoiDung);
            }
            return Redirect("/404");
        }

        [HttpPost]
        public ActionResult CapNhat(NguoiDung nguoidung)
        {
            if (ModelState.IsValid)
            {
                var dao = new NguoiDungDAO();

                if(nguoidung.MatKhau == null)
                {
                    nguoidung.MatKhau = dao.TimTheoTenTK(nguoidung.TaiKhoan).MatKhau;
                }
                else nguoidung.MatKhau = Encryptor.MD5Hash(nguoidung.MatKhau); //Mã hóa

                var KetQua = dao.CapNhat(nguoidung);
                if(KetQua > 0)
                {
                    DatThongBao("Cập nhật thông tin người dùng thành công!", LoaiThongBao.ThanhCong);
                    return RedirectToAction("Index");
                }
                else
                {
                    DatThongBao("Cập nhật thông tin người dùng không thành công!", LoaiThongBao.Loi);
                }
            }
            return View();
        }

        public ActionResult Xoa(string id)
        {
            var dao = new NguoiDungDAO();
            var NguoiDung = dao.TimTheoTenTK(id);

            if(NguoiDung != null)
            {
                var KetQua = dao.Xoa(id);
                if(KetQua > 0)
                {
                    DatThongBao("Xóa người dùng thành công!", LoaiThongBao.ThanhCong);
                }
                else
                {
                    DatThongBao("Xóa người dùng không thành công!", LoaiThongBao.Loi);
                }
                return RedirectToAction("Index");
            }
            return Redirect("/404");
        }

        [HttpPost]
        public JsonResult ThayDoiTrangThai(string id)
        {
            var dao = new NguoiDungDAO();
            var KetQua = dao.ThayDoiTrangThai(id);
            return Json(new { 
                TrangThai = KetQua
            });
        }
    }
}

ThuVien/Areas/Admin/Views/NguoiDung/CapNhat.cshtml
@model Models.EF.NguoiDung

@{
    ViewBag.Title = "Cập Nhật Thông Tin Người Dùng";
    Layout = "/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Header{
    Người Dùng
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm Mới</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("CapNhat", "NguoiDung", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Quyen)

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label>Tài khoản</label>
                        @Html.TextBoxFor(model => model.TaiKhoan, new { @class = "form-control", @required = "required", ReadOnly = "ReadOnly" })
                        @Html.ValidationMessageFor(model => model.TaiKhoan)
                    </div>
                    <div class="col">
                        <label>Mật khẩu</label>
                        @Html.TextBoxFor(model => model.MatKhau, new { @class = "form-control"})
                        @Html.ValidationMessageFor(model => model.MatKhau)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="custom-control custom-switch">
                    @Html.CheckBoxFor(model => model.TrangThai, new { @class = "custom-control-input", @id = "TrangThai" })
                    <label class="custom-control-label" for="TrangThai">Kích hoạt</label>
                </div>
            </div>
            <div class="form-group">
                <center>
                    <input type="submit" value="Hoàn thành" class="btn btn-primary" />
                </center>
            </div>
        }
    </div>
</div>

ThuVien/Areas/Admin/Views/NguoiDung/Index.cshtml
@model PagedList.IPagedList<Models.EF.NguoiDung>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Người Dùng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Header{
    Người Dùng
}
@section jsFooter{
    <script src="~/Assets/Admin/js/controller/NguoiDungController.js"></script>
}
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <span class="m-0 font-weight-bold text-primary">
            Danh sách
            <span style="float: right">

                <a href="/Admin/NguoiDung/ThemMoi" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Thêm mới</span>
                </a>

            </span>
        </span>

    </div>
    <div class="card-body">
        <div class="table-responsive">

            @using (Html.BeginForm("Index", "NguoiDung", FormMethod.Get))
            {
                <div style="padding: 3px; margin-bottom: 20px; width: 24.5rem">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Từ khóa" name="TimKiem" value="@ViewBag.TimKiem">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </div>
            }
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Tài khoản</th>
                    <th>Quyền</th>
                    <th>Trạng Thái</th>
                    <th style="text-align: center">Công cụ</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    var Quyen = "";
                    if(item.Quyen == "SinhVien")
                    {
                        Quyen = "Sinh Viên";
                    }
                    else if(item.Quyen == "NhanVien")
                    {
                        Quyen = "Nhân Viên";
                    }
                    else
                    {
                        Quyen = item.Quyen;
                    }

                    <tr>
                        <td>@item.TaiKhoan</td>
                        <td>@Quyen</td>

                        <td>
                            <a name="TrangThai" data-id="@item.TaiKhoan" href="#" class="@(item.TrangThai == true ? "btn btn-primary" : "btn btn-danger")">
                                @(item.TrangThai == true ? "Kích hoạt" : "Khóa")
                            </a>
                        </td>
                        <td align="center">
                            <a href="/Admin/NguoiDung/CapNhat/@item.TaiKhoan" class="btn btn-primary btn-circle btn-sm" title="Sửa">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="/Admin/NguoiDung/Xoa/@item.TaiKhoan" class="btn btn-danger btn-circle btn-sm" title="Xóa" data-toggle="modal" data-target="#XoaNguoiDung-@item.TaiKhoan">
                                <i class="fas fa-trash"></i>
                            </a>

                            <div class="modal fade" id="XoaNguoiDung-@item.TaiKhoan" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Xóa Người Dùng</h5>
                                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">Xóa người dùng này khỏi CSDL?</div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                                            <a class="btn btn-primary" href="/Admin/NguoiDung/Xoa/@item.TaiKhoan">Xóa</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }

                </tbody>
            </table>
            @Html.PagedListPager(Model, Trang => Url.Action("Index", new { Trang, TimKiem = @ViewBag.TimKiem }))
        </div>
    </div>
</div>

ThuVien/Areas/Admin/Views/NguoiDung/ThemMoi.cshtml
@model Models.EF.NguoiDung

@{
    ViewBag.Title = "Thêm Mới Sinh Viên";
    Layout = "/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Header{
    Sinh Viên
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm Mới</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("ThemMoi", "NguoiDung", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label>Tài khoản</label>
                        @Html.TextBoxFor(model => model.TaiKhoan, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.TaiKhoan)
                    </div>
                    <div class="col">
                        <label>Mật khẩu</label>
                        @Html.TextBoxFor(model => model.MatKhau, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.MatKhau)
                    </div>
                    <div class="col">
                        <label>Quyền</label>
                        <select name="Quyen" id="Quyen" class="form-control">
                            <option value="SinhVien">Sinh viên</option>
                            <option value="NhanVien">Nhân viên</option>
                            <option value="Admin">Admin</option>
                        </select>
                        @Html.ValidationMessageFor(model => model.Quyen)
                    </div>

                </div>
            </div>
            <div class="form-group">
                <div class="custom-control custom-switch">
                    @Html.CheckBoxFor(model => model.TrangThai, new { @class = "custom-control-input", @id = "TrangThai" })
                    <label class="custom-control-label" for="TrangThai">Kích hoạt</label>
                </div>
            </div>
            <div class="form-group">
                <center>
                    <input type="submit" value="Hoàn thành" class="btn btn-primary" />
                </center>
            </div>
        }
    </div>
</div>